### ISSUE TITLE
Set up Travis-CI integration for flake8 checking

### ISSUE THREAD

**Issue by davehunt** [mozilla/oneanddone-tests#30]
We should use Travis-CI for basic code checking. In order to do this, we need to set up `.travis.yml` as follows:

```yml
language: python
python: 2.7
install: "pip install flake8"
script: "flake8 ."
```

Also, create a `setup.cfg` file to configure `flake8` that is the same as https://github.com/mozilla/mcom-tests/blob/master/setup.cfg
